### ISSUE TITLE
Specify permissions required for service account

### ISSUE THREAD

**Issue by krtk6160** [RafikFarhad/push-to-gcr-github-action#11]
The README.md currently does not specify which permissions are required by the action to run successfully. This leads to trial and error by users to ensure that only the necessary permissions are granted to the service account being used for this particular action.

It would be great if all the permissions required are listed as it would save users time by just creating a role with those permissions and using the same for the service account.

**Comment by RafikFarhad** [comment]
Hey @krtk6160, I am glad that you pointed the issue.
It is a horrible mistake from my side that I did not put the necessary permission required by the action. 
I will add a section specifying the least required permission ASAP!

And many many thanks 🤜

**Comment by krtk6160** [comment]
> Hey @krtk6160, I am glad that you pointed the issue.
> It is a horrible mistake from my side that I did not put the necessary permission required by the action.
> I will add a section specifying the least required permission ASAP!
> 
> And many many thanks 🤜

No worries. Thanks for building this action.

**Comment by RickRen7575** [comment]
I would love the same documentation! Thank you!
