### ISSUE TITLE
Build args json problem

### ISSUE THREAD

**Issue by saar-win12** [RafikFarhad/push-to-gcr-github-action#15]
Hey, tried to pass JSON through the build args
and it looks like:

`TEST={ --build-arg "type": --build-arg "service_account" --build-arg "project_id": `

any other options?
tnx.

**Comment by RafikFarhad** [comment]
You should handle `"` with `\"` because in the end it will be passed as a shell command.
So try with this:
`TEST="{ --build-arg \"type\": --build-arg \"service_account\" --build-arg \"project_id\":"`
And one more thing, if the right side contains any non alphanumeric character then you should enclose them with `"`.

**Comment by saar-win12** [comment]
Ya, but it's a service account JSON, it adds it for something like 100
lines :|

**Comment by RafikFarhad** [comment]
Got it, I was in the same situation. As far as I remember I placed the service account json in github secrets.
And the other thing is that, passing your account json in the action file may not be a good idea. 
If you really want that just replace all `"` with `\"` and place in the action file.

**Comment by saar-win12** [comment]
I really need it,
do you have a script or something to do that?  
thanks

**Comment by RafikFarhad** [comment]
Open with any code editor, press CTRL+R or CMD+R. You'll find a interface to do this.
Or you can [use this](http://www.unit-conversion.info/texttools/replace-text/).

**Comment by saar-win12** [comment]
Hey, after I added the "\", it was like that:
docker build  --build-arg SERVICE_ACCOUNT=$(cat --build-arg *** --build-arg \"type\": --build-arg \"service_account\" --build-arg \"project_id\": --build-arg \"***\" --build-arg \"private_key_id\":

**Comment by RafikFarhad** [comment]
Could please share more context about what are you trying to do?

**Comment by saar-win12** [comment]
I'm trying to take secret and pass it in build args.
$(cat {{ secrets.blabla }}), the file is ok,
but the build args separate it according to the spaces in the file :|

**Comment by RafikFarhad** [comment]
Could you please try `SERVICE_ACCOUNT ="$(cat {{ secrets.blabla }})"` ?

**Comment by RafikFarhad** [comment]
Thanks @saar-win12 for using this action and also sharing the issue with us. Feel free to reopen if it is not solved yet. Cheers 🍻
