### ISSUE TITLE
Not able to login to docker

### ISSUE THREAD

**Issue by raghavmri** [RafikFarhad/push-to-gcr-github-action#16]
Hey there, 
 I was using your module in my action for the past 2 days and I didn't have any issues with the deployment but yesterday after GitHub faced the downtime I tried to run a deployment without making any sort of changes to my job and got the following error. I am proving the service account JSON file in base64encoded form

![image](https://user-images.githubusercontent.com/62844922/128977467-ce468281-0c16-4714-9e01-10e372de4733.png)

**Comment by raghavmri** [comment]
May be if you add this to line 28 in entrypoint.sh `docker login -u _json_key -p $( cat /tmp/key.json )  https://$INPUT_REGISTRY; then` It might work

**Comment by RafikFarhad** [comment]
Did you try recently? 
Is that occurring now?

**Comment by raghavmri** [comment]
Yeah I did try recently and faced this issue I even tried yesterday

**Comment by bitqr** [comment]
Same problem here. I encoded the json key file in base 64 as required in the doc. Should I try something else?

**Comment by RafikFarhad** [comment]
Thanks @raghavmri for reporting. Please allow me sometime, I'll take a look and will resolve the issue ASAP!

**Comment by RafikFarhad** [comment]
Hi @raghavmri, Thanks for using this action and sorry for late reply.
I was observing this issue and searching in other repo for similar kind of error. As my repos are running fine with this action I was unable to debug this.
I think it is not related to this action and it is working for me and some of my friends. 

Is it still occurring from your end? 
Please feel free to reopen this if this occurs again.
