### ISSUE TITLE
Please support targets

### ISSUE THREAD

**Issue by tschm** [RafikFarhad/push-to-gcr-github-action#2]
We use Dockerfiles with targets. Would be nice if your tool supports that... part of the docker standard api

**Comment by RafikFarhad** [comment]
Thanks for your suggestion 😀.
Docker target build will be a big enhancement for this action. It will be supported by your tool by this weekend I hope. 😊

**Comment by RafikFarhad** [comment]
Support for docker targeted build implemented.
Thanks @tschm for this awesome suggestion. 
Closing this.
