### ISSUE TITLE
If image_tag input is separated with  ", " no push occurs

### ISSUE THREAD

**Issue by thedmeyer** [RafikFarhad/push-to-gcr-github-action#20]
If the image_tag variable has an input like below, a push never occurs and no error is given.
```
image_tag: latest, another-tag
```

Is this correct behavior, to assume a true CSV input?
such that:
```
image_tag: latest,another-tag
```

```bash
function split_csv() {
    IFS=','
    csv_data=$1
    local -n global_list_array=$2
    for i in $csv_data; do
        global_list_array+=($i)
    done
    unset IFS
}
```

**Comment by RafikFarhad** [comment]
Hi @thedmeyer, thanks for using this action.
If the input is not a CSV or contains unsupported character (in this case whitespace) then this action should throw error. 
I'll fix this behaviour soon. Thanks for reporting.

**Comment by RafikFarhad** [comment]
Hi @thedmeyer, this issue has been handled from v4.1. Now the action will try to sanitize the image name by removing whitespaces and empty tag names. Also, `latest` will be used when the `tag_names` is un-persable. 
Thanks for reporting the issue.
