### ISSUE TITLE
Example is not clear on why it needs `google-github-actions/setup-gcloud` step as a prerequisite

### ISSUE THREAD

**Issue by RomanKornev** [RafikFarhad/push-to-gcr-github-action#21]

**Comment by RafikFarhad** [comment]
Thanks @RomanKornev, I will check the `gcloud` dependency if that is really needed by this action. 
This step is added in the latest version. 
If that is not necessary I will update the example and documentation. 
Thanks for pointing this out. 👍🏼

**Comment by RafikFarhad** [comment]
Hi @RomanKornev, apologies for the late response on this. You are right, that dependency is needed anymore. In v4.1, that dependency has been dropped from everywhere.
Thanks for using this action.
