### ISSUE TITLE
Unable to use service account key

### ISSUE THREAD

**Issue by kryptonite0** [RafikFarhad/push-to-gcr-github-action#22]
Hi there, 

Thank you for making this awesome action available!

I'm using the build and push workflow but I'm getting this error:
```
Authenticating docker to gcloud ...
Failed to decode gcloud_service_key -- did you forget to encode it using 'python -m base64 -e < yourkey.json'?
```
I created a json key for a service account and pasted the key into a github secret, which is used by the workflow. Any idea what this error could be due to?

**Comment by RafikFarhad** [comment]
Hi @kryptonite0, thank for using this action.
Did you encode your json as base64 before pasting as github secret?

**Comment by kryptonite0** [comment]
I did, but not using the command `python3 -m base64 -e < key.json`. Now I used that command and it worked fine ^.^ Thanks
