### ISSUE TITLE
Github Workflow executes forever if Docker build fails.

### ISSUE THREAD

**Issue by MisterJimson** [RafikFarhad/push-to-gcr-github-action#24]
We introduced a bug that caused the docker file to fail to build. I would expect the Github workflow to exit with an error.

Instead the publish to GCR step just continues forever. This uses up build time and makes debugging the problem difficult.

**Comment by RafikFarhad** [comment]
I am thinking about what type of solution will be suitable here. 
Maybe a timeout for publishing to GCR step? Do you have any suggestions?

**Comment by MisterJimson** [comment]
Locally the docker build command exists with a non-zero exit code. So I would want the action to propagate that exit code out to the action.

As an example

```
    if docker build .; then
        echo worked
    else
        echo failed
    fi
```

When I run that bash script, the docker build starts, fails, then I see "failed" as the output. We should be able to capture the exit code and fail the workflow step.

**Comment by RafikFarhad** [comment]
Are not we doing the same here:
https://github.com/RafikFarhad/push-to-gcr-github-action/blob/master/entrypoint.sh#L57-L62

**Comment by RafikFarhad** [comment]
Thanks, @MisterJimson for using this action for sharing your valuable suggestion. Seems like it has been no longer an issue for you so closing this.
