### ISSUE TITLE
How to authenticate using google-github-actions/auth

### ISSUE THREAD

**Issue by GoldenMouse** [RafikFarhad/push-to-gcr-github-action#26]
I'm using `google-github-actions/auth` for federated credentials.
I'm having a difficult time making this work with your action.

`google-github-actions/auth` creates "$GOOGLE_APPLICATION_CREDENTIALS" file for me and I was able to base64 encode this.
But when I feed it to `RafikFarhad/push-to-gcr-github-action@v4` it throws this error:

```Error response from daemon: Get "https://gcr.io/v2/": unknown: Missing "client_email" in json key.```

**Comment by RafikFarhad** [comment]
Thanks, @GoldenMouse for bringing this up. Everybody is recommending using federated credentials over the JSON key scheme and I can not agree more. This action also should support this. Today I have released 4.1 with some bug fixes and input sanitization. I started to implement federated credentials for this action and soon it will be available as the next version (v5.0 or v4.2 depending on the plan of supporting JSON Scheme). Thanks for being with the action. I will update this thread about the release.

**Comment by gnomohf** [comment]
Hi! Would this include using `gcloud auth configure-docker` to avoid this warning message?:
`WARNING! Your password will be stored unencrypted in /github/home/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store`

According to this [link](https://cloud.google.com/container-registry/docs/advanced-authentication#gcloud-helper) if you use `gcloud auth login` (or `google-github-actions/auth`) you can just execute `gcloud auth configure-docker`. Without the need to ask for the `gcloud_service_key`. Am I Right?

**Comment by RafikFarhad** [comment]
Hi @gnomohf, thanks for your suggestion. This action used `gcloud` previously, and we removed `gcloud` installation step when we discovered that we can skip it. It is our bad we ignored the warning. 
I will bring back the `gcloud auth login` approach so that this warning goes away. 

🚀

**Comment by RafikFarhad** [comment]
Hi @GoldenMouse and @gnomohf,
the latest version [`v5-beta`](https://github.com/RafikFarhad/push-to-gcr-github-action/releases/tag/v5-beta) can be used with `google-github-actions/auth`.
Also, it uses `gcloud auth configure-docker`, so, no warning for `.. Your password will be stored unencrypted .. `.
 
Thanks for using this action and giving good suggestions. 

`v5-beta` will be moved to `v5` after some adoption and testing by end-users.
