### ISSUE TITLE
feature request: allow --build-arg to passed to docker build

### ISSUE THREAD

**Issue by hwmrocker** [RafikFarhad/push-to-gcr-github-action#6]
`--build-arg` is very useful to pass a version string during build time to the docker image.

**Comment by RafikFarhad** [comment]
Thanks @hwmrocker for pointing that out. I will try to implement this by the next week. 🤛

**Comment by dodizzle** [comment]
I had already added build args in my fork and forgot to commit it.
https://github.com/RafikFarhad/push-to-gcr-github-action/pull/7
Enjoy.

**Comment by RafikFarhad** [comment]
Hey @hwmrocker, this feature has been implemented by @dodizzle and released with the tag `v3.0.1`.
Thanks for the support.
Cheers 🍻 🍻 🍻
