### ISSUE TITLE
Error finding Dockerfile

### ISSUE THREAD

**Issue by nrfribeiro** [RafikFarhad/push-to-gcr-github-action#9]
Hi,
I'm getting the following error when you are running the following command.  
docker build   -t edi-safety-proxy:temporary --file ./Dockerfile .

Error
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /github/workspace/Dockerfile: no such file or directory

My Doockerfile is in the root of github. Can you help?

**Comment by RafikFarhad** [comment]
Hello @nrfribeiro , thanks for using the  `push-to-gcr-github-action`

It will be more helpful to debug if you provide your `.yml` file for the github-action. 
It seems like you are passing `dockerfile` parameter though it is not needed.
Are you specifying `dockerfile` in the `*.yml` file? 
If your Dockerfile is the root directory, then you don't have to specify that.

**Comment by RafikFarhad** [comment]
Please reopen this if your issue is not solved yet. Thanks ✊

**Comment by krtk6160** [comment]
> Hi,
> I'm getting the following error when you are running the following command.
> docker build -t edi-safety-proxy:temporary --file ./Dockerfile .
> 
> Error
> unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /github/workspace/Dockerfile: no such file or directory
> 
> My Doockerfile is in the root of github. Can you help?

I had the same issue. I solved it by using a checkout action right before the build docker image action.

@RafikFarhad I think it would be helpful to include this in the README.md file.

**Comment by RafikFarhad** [comment]
Hello @krtk6160,
Thanks for your great observation. 
I have added the `checkout` step in all the example.

**Comment by RafikFarhad** [comment]
Hey @nrfribeiro, please follow the current example from the `ReadMe.md`.
There is one extra steps that you need to be added.
Sorry for the inconvenience. 
Hope this action will help you building awesome systems.
